Initial thoughts
christfellowshipchurch/apollos-api pull request #132
Opened 2020-09-16 19:21 UTC by asleepingpanda

This PR is intended to discuss and plan for a deprecation/update of fields in the EventContentItem, Event, and LiveStream interfaces in preparation for

1. Live Stream Chat
2. Organizing event times on the Mobile App by category

2020-09-16 19:22 UTC, asleepingpanda commented
@hellogerard @rkdavidson by introducing a the `Node` interface to the `LiveStream` type, do we even need a "ChannelId"? or can we just use a Live Stream's `id` as the channel id in Stream?

2020-09-16 20:28 UTC, rkdavidson commented
> do we even need a "ChannelId"? or can we just use a Live Stream's id as the channel id in Stream?

@asleepingpanda IMO, it feels more "future proof" to have this be an explicit field that clients query for.
We already have to do a transformation to strip the `Prefix:` part of the `id`, so there's client parsing logic that'd need duplicated but more importantly — somewhat prone to change.
By resolving it on the server, we avoid problems of worrying about client versions etc.

2020-09-16 20:34 UTC, asleepingpanda commented
@rkdavidson that makes a lot of sense. I wonder if we should introduce an interface called `Chat` or `ChatChannel` in order to future proof this even MORE. This way that interface with a ChatChannelId could be stream or not stream. It could also allow for Group Chat, DM's between Group members OR Live Stream.

If that sounds decent, I'll whip that together. Thinking like

`
type ChatChannel implements Node {
   id: ID!
   name: String!
}

interface ChatChannelNode {
   chatChannel: ChatChannel
}
`

2020-09-16 20:36 UTC, asleepingpanda commented
And then we could say `type LiveStream implements Node && ChatNode { ... }` and then later on say `type Group implements ChatNode { ... }`

2020-09-16 20:52 UTC, rkdavidson commented
Hmm, interesting line of thought. I actually lean the opposite way — not that I think that's the "wrong" direction, but more that it feels like a solution without a problem right now.

Stream.io's services handle the vast majority of all things chat related, so introducing our own concepts and domain models around it feels risky and prone to conflicts or churn over time.

I suppose it depends on the roadmap — i.e. for Group chats, I could see a simple `String` field being added to that type to resolve the channel ID that group uses.

To devil's advocate against myself... the second we have additional fields to provide, we'd be in trouble.
Hypothetically that `ChatNode` type could be _all_ the parameters needed for the channel — not just the ID.

I.e. essentially something like:

```javascript
const { data } = useQuery(GET_LIVESTREAM);
const { chatChannel } = data;

// Later, when the data is back...
const channel = StreamChatClient.createChannel(
  chatChannel.type, // "livestream"
  chatChannel.id, // some ID
  chatChannel.metadata, // { image, name, uploads: false, eventContentItemId, etc }
);
```

This type of setup would allow us to more easily add Rock fields to manage how the chat channel is presented or behaves.
i.e. a Group leader (or someone) could change a Group's chat name and image via Rock.
Flip side of _that_, it's easier to use Stream.io's client API for that...

I think `LiveStream` implementing the `ChatNode` interface feels stranger than if it simply "has" a separate child entity called `ChatChannel` that could be shared across other types in the API.

Like:
```graphql
type LiveStream implements Node {
  # ... existing stuff ...
  chatChannel: ChatChannel
}

type ChatChannel {
  id: ID!
  name: String
  image: String
  metaData: ChatChannelMetaData
}

type ChatChannelMetaData {
  relatedTo: ID! # Like "EventContentItem:ABC123"
  someCustomField: String
  # ...
}
```

Then, you could add a `chatChannel` resolver for `Group` type, too. That data could be derived from Rock etc.

I've gotta percolate on this a bit more, but this is an interesting architectural challenge 🤔.

2020-09-16 20:55 UTC, rkdavidson commented
Oh 🤦‍♂️ I'm sorry, @asleepingpanda — I think you were suggesting in the first place what I ended up suggesting! Doh!

Here's a new fresh idea I just had — _what if we do <repeats everything Caleb said, but louder>_??

2020-09-16 21:00 UTC, asleepingpanda commented
No I hear what you're saying, though, and I think there's a lot of value in generalizing that `ChatChannel` to not implement node so that we can just simply use a string identifier and not have to worry about parsing an Apollos ID on the client.

I'm gonna commit an update real quick to see what you guys think about it based on the above

2020-09-16 21:24 UTC, asleepingpanda commented
@rkdavidson check that update out and let me know what you think. It's very similar to the paradigm that @vinnyjth is introducing in Apollos (I hope so? lol)

2020-09-16 21:42 UTC, rkdavidson reviewed
Left some quick off-hand comments, but happy to look closer and/or chat tomorrow about it.
I also generally defer to the resident graphql wizard 🧙‍♂️ @hellogerard for big problems like this 🙈.

2020-09-16 21:42 UTC, rkdavidson commented on src/data/events/schema.js
> +    events: [Event] @deprecated(reason: "Events are no longer organized by limiting them to a physical campus. Events are organized into categories. Please reference 'EventContentItem' instead")
So if I'm following, there will no longer be _any_ association of **Campuses** and **Events**?

2020-09-16 21:42 UTC, rkdavidson commented on src/data/event-content-item/schema.js
> +    categories: [EventInstanceCategories]
Getting tripped up in my head on terminology here — what's the thinking behind the term **Category**?
Is this like "Join Church Online" or "CF Students", etc?

i.e. some sort of "base" event that occurs many times as `instances`/individual `Event` entries?

2020-09-16 21:42 UTC, rkdavidson commented on src/data/live-stream/schema.js
> +        members: [Person]
I think I like the general `type ChatChannel`, but not this `members` part — could open a can of worms, at no apparent value add.
This is easy to obtain via Stream.io chat client and that's the source of truth ultimately.

Though, you could definitely integrate the Stream.io client in the API to make platform calls on behalf of users, if you'd like.
This could be useful for things like adding a `chatChannels` resolver on `AuthenticatedUser` that, completely server side, queries the list of all channels a member is in and returns them.
But, technically that data response would be a different model than the custom `ChatChannel` in our API. It'd have a lot of extra data etc.

2020-09-17 13:51 UTC, asleepingpanda commented on src/data/events/schema.js
> +    events: [Event] @deprecated(reason: "Events are no longer organized by limiting them to a physical campus. Events are organized into categories. Please reference 'EventContentItem' instead")
For the time being, I've made the CMS much more generic to allow for you to type in your own label, so it's no longer guaranteed to be campus.

Eventually we'll want to be able to take advantage of tagging an event to be specific to a group of people (by campus, age, interests, etc) but I want to rethink that tooling when we get back to that place.

2020-09-17 13:52 UTC, asleepingpanda commented on src/data/event-content-item/schema.js
> +    categories: [EventInstanceCategories]
Yeah so I like that you bring this up! I wasn't really sure what to call it, but I wasn't liking `categories` much, either.

The idea here is that the visual dropdown will have information organized by a label. That label could be "Palm Beach Gardens" or "Join Us Online". It's used as a way to describe the "instances" of an event that you are looking at.

2020-09-17 13:53 UTC, asleepingpanda commented on src/data/live-stream/schema.js
> +        members: [Person]
Yeah I threw it in there cause why not, but I figured it was already a problem solved by stream. Remove for the time being you think??

2020-09-17 14:19 UTC, rkdavidson commented on src/data/events/schema.js
> +    events: [Event] @deprecated(reason: "Events are no longer organized by limiting them to a physical campus. Events are organized into categories. Please reference 'EventContentItem' instead")
That sounds great! Tagging is a much more robust idea 👍.

2020-09-17 14:37 UTC, hellogerard reviewed
Left some comments. Some may be off base. I still don't fully grasp the situation.

In general, I feel like events should be modeled like this:


**EventContentItem**

This is the abstract event, which has all the demographic info (name, image, description, etc)

**Event**

This is the _instance_ of the `EventContentItem`. It would have a time and a place. The place could be a physical campus, a Zoom link, or have a livestream. It could have any query-able attributes, such as "is it live?", "is it physical?".

Both type should be queryable at a high-level. You should be able to travel from one to the other. You could also query events by their locations, or by their date/times.

Am I close? Is something like this possible to setup in Rock? Is it already?

2020-09-17 14:37 UTC, hellogerard commented on src/data/event-content-item/schema.js
> +    categories: [EventInstanceCategories]
Echoing @rkdavidson, what would `EventInstanceCategories` be for? What would this new layer of abstraction be used for?

```
EventContentItem
  ↓
EventInstanceCategories
  ↓
Event
```

2020-09-17 14:37 UTC, hellogerard commented on src/data/live-stream/schema.js
> +        members: [Person]
Agree, not necessary right now. Let's keep things having single responsibility, and for members right now that would be the Stream client on the app.

2020-09-17 14:37 UTC, hellogerard commented on src/data/live-stream/schema.js
> +    interface ChatChannelNode {
At first, I didn't know what this interface would be for, but now i remember that the new Groups could have chat, etc. So this makes sense.

2020-09-17 14:37 UTC, hellogerard commented on src/data/live-stream/schema.js
> +    interface LiveNode {
But not sure this interface is necessary right now? If I am reading this correctly, we might have other types of  content items that have a livestream? Right now, things may in transition, but at the end of the day, isn't the only thing with a livestream the weekend service? We don't want to overengineer things.

2020-09-17 14:37 UTC, hellogerard commented on src/data/live-stream/schema.js
> +    extend EventContentItem implements LiveNode
I thought the `Event` would implement `LiveNode`, not the `EventContentItem`. Isn't the `Event` the "instance", which would have he specific livestream (little "e") event?

2020-09-17 14:42 UTC, rkdavidson commented on src/data/live-stream/schema.js
> +        members: [Person]
@asleepingpanda Yeah, your call but this feels like all risk no reward at this stage — the methods Stream's SDK provide give us really clean, simple mechanisms to get this info _once we know the channel ID_:
https://getstream.io/chat/docs/query_members/?language=js

```javascript
// query members by user.name
const {members} = await channel.queryMembers({'name':'tommaso'})
console.log(members)

// query members with name containing tom
channel.queryMembers({name:{"$q":'tom'}})

// autocomplete members by user name
channel.queryMembers({name:{"$autocomplete":'tomm'}})

// query member by id
channel.queryMembers({id:'tommaso'})

// query multiple members by id
channel.queryMembers({id:{'$in:'['tommaso','thierry']}})

// query channel moderators
channel.queryMembers({is_moderator:true})

// query for banned members in channel
channel.queryMembers({banned:true})

// query members with pending invites
channel.queryMembers({invite:'pending'})

// query all the members 
channel.queryMembers({})

// paginate channel members
channel.queryMembers({}, {}, {limit:10,offset:10})

// order results by member created at descending
channel.queryMembers({}, {created_at:-1})
```

2020-09-17 14:50 UTC, rkdavidson commented on src/data/event-content-item/schema.js
> +    categories: [EventInstanceCategories]
Ah, gotcha! I don't _hate_ the term **Categories**, it just — at this super early seeding stage — wasn't immediately intuitive without examples to go look for.

I suppose we could also describe them as **EventGroups**, arbitrary collections of specific **Event** instances, but that conflates it with the "real" **Groups** term.

@hellogerard had some questions about this, so to prevent a crazy spread out convo, I'll move the rest of my thoughts to the PR as a whole.

2020-09-17 14:53 UTC, asleepingpanda commented on src/data/event-content-item/schema.js
> +    categories: [EventInstanceCategories]
I love the idea of EventGroups!! That seems to be so much more immediately intuitive. It's a group of similar events, labeled by some name (All time for Palm Beach Gardens, all times for Johan's Coffee Shot, and so on)

I'm gonna make this language update

2020-09-17 15:29 UTC, asleepingpanda commented on src/data/live-stream/schema.js
> +    interface LiveNode {
This is actually a Node interface that is coming in Core Apollos 1.6.0. I am adding it here so that I can just keep in mind the new Apollos Node Interface convention.

2020-09-17 15:30 UTC, asleepingpanda commented on src/data/live-stream/schema.js
> +    extend EventContentItem implements LiveNode
Yeah we can discuss it later on (during our touch base) but this convention was suggested from @vinnyjth after a conversation with him about the upcoming Node Interface convention being introduced in Apollos.

2020-09-17 16:05 UTC, hellogerard commented on src/data/event-content-item/schema.js
> +    categories: [EventInstanceCategories]
If that's the case, would they just be different `EventContentItems`?

2020-09-17 16:08 UTC, hellogerard commented on src/data/live-stream/schema.js
> +    interface LiveNode {
Oh right. I remember seeing the chatter in Slack. So they want all livestreams to implement `LiveNode`. All the interfaces get confusing to me, but that may just be a characteristic of Apollos Core.

2020-09-17 20:28 UTC, asleepingpanda commented
@rkdavidson @hellogerard could I get one more quick look at this before I get in there and add the necessary resolvers??

2020-09-17 21:10 UTC, hellogerard commented
Overall, I still think this looks good.  Do I have this model right?

```
Node                            Node
  ↓                                  ↓
EventContentItem → LiveStream → ChatChannel
  ↓   
EventGrouping
  ↓
Event
```

Noticed a couple things on one last run thru:

1. Does it make sense to just put the chat stuff in a folder called `chat` instead of `chat-channel`?

1. Totally out of curiosity, but is this a breaking change? `type LiveStream implements Node` 


Lastly, to be super-specific, will this query still work as it does today on the client? This is how the Media Player gets the URI and content ID to be used as the channel ID. I get that the `liveStream` will have a `chatChannel` now for the channel ID, but otherwise?  If this won't work, interestingly, and we can't use Apollo local state for the Media Player, then we may have to go the Context route after all, like we talked the other day!

```gql
  query getLiveContent {
    liveStreams {
      isLive
      media {
        sources {
          uri
        }
      }
      contentItem {
        id
      }
    }
  }
```

2020-09-18 16:14 UTC, asleepingpanda commented
Ah yeah that's an interesting point. I will have to ask @conrad-vanl cause he mentioned that one of the other churches is having LiveStream extend node. I don't think it's 100% necessary for what we're doing, though, since we do have the `ChatChannel`, now.

Let me look and see if we can't update the Live Streams query on the front end to include our new data fields.

2020-09-18 16:22 UTC, asleepingpanda commented
@hellogerard looks like we can update the `LIVE_STREAM_FRAGMENT` from within the `loadConfig.js` which I think _should_ make us able to access that id and the ChatChannel

2020-09-23 21:11 UTC, asleepingpanda commented
I think this PR is in a pretty solid place AND all the deprecation notices are in place, although everything should be backward compatible.

2020-09-23 21:15 UTC, asleepingpanda commented on src/data/live-stream/resolver.js
> +      CheckInable.getByContentItem(id),
@jordanwade I don't think this is going to work. CheckInable assumes the Id to reference a Rock Group and this Id actually references a Rock Attribute Matrix Item.

Along with `id`, there should also be a prop called `attributeValues` that should contain `checkInGroup.value` which will either be a Rock Group Guid or an empty String. Can just return `null` if it's an empty string and then return `CheckInable.getByContentItem(guid)` if the Guid exists.

2020-09-24 14:45 UTC, jordanwade commented on src/data/live-stream/resolver.js
> +      CheckInable.getByContentItem(id),
@asleepingpanda Thanks, that explains why I was having so many problems. Looking into now to see if I can get it working correctly.

2020-09-24 14:46 UTC, asleepingpanda commented on src/data/live-stream/resolver.js
> +      CheckInable.getByContentItem(id),
I'll go ahead and add a Group to one of those Live Streams so that you have real data to work with

2020-10-05 19:21 UTC, jordanwade commented
@asleepingpanda is there a need for corresponding branches for the Web App and the Mobile App for these changes to not break livestream/events? It looks like you are changing some things might cause queries for `events` to now need to be structured as `eventGroupings`?

The reason I ask is it seems that the query `GET_LIVE_CONTENT` for the media-player isn't working correctly. Which I need for `checkin`. 
https://github.com/christfellowshipchurch/apollos-app/blob/753b9d81e50c058b1732d1c0a91f60e48bc4a519/src/media-player/index.js#L30-L53

2020-10-05 19:30 UTC, jordanwade commented
@asleepingpanda Now that I wrote that, is that I just need to update that query `GET_LIVE_CONTENT`?

2020-10-05 19:33 UTC, asleepingpanda commented
@jordanwade that _sounds_ correct. And yes, we will need to update the front end of the web app as well. I'm glad you brought that up cause I haven't walked @dzwood through this branch yet.

We are also in some discovery with check in and Rock and we may end up needing to include a scheduleId with check in. When I have more info I'll pass it along. Keep on going with this as is, but just know that we might need to expand it a little bit

2020-10-07 14:35 UTC, jordanwade requested changes
I've shifted gears way from this branch since there is still discover work being done around 'checkin' and making sure groups/events always have 'scheduleID'. 

I discovered mobile and web needs corresponding updates to queries since this moves towards using `relatedNode` and the shape of events has changed to use a matrix in Rock. It does seem that things are backward compatible, but I would be more comfortable approving this if those front-end/client PRs were ready to go too.

2020-10-23 20:13 UTC, merged