The Big Merge
christfellowshipchurch/apollos-api pull request #144
Opened 2020-10-23 19:57 UTC by asleepingpanda

This PR is set up to consolidate the following changing into 1 single merge:

1. StreamChatChannel schema introduction
2. New Events Schema
3. Check In updates

2020-10-23 20:25 UTC, asleepingpanda commented
@rkdavidson we should be good to completely remove the `chatChannelId` from the Groups schema once the front end is confirmed to no longer use that. I left it in there for the time being just as a reminder that we need to update the front end for launch.

2020-10-26 15:11 UTC, jordanwade requested changes

2020-10-28 14:02 UTC, rkdavidson approved these changes

2020-10-28 14:52 UTC, asleepingpanda commented
@jordanwade removed all unneeded console logs

2020-10-28 15:09 UTC, jordanwade approved these changes

2020-10-28 15:22 UTC, merged