[Chat] Add channelType to StreamChatType schema
christfellowshipchurch/apollos-api pull request #158
Opened 2020-11-03 03:58 UTC by rkdavidson

Currently, the client apps have a hard coded `channelType` value used to initiate a chat channel.
Events use `"livestream"`, groups use `"group"`.

This PR lifts the resolution of that value for various chat contexts to the api, as `streamChatChannel.channelType`.

Types like `GroupItem`, `LiveStream`, etc can resolve the value independently for their specific context.

2020-12-09 21:49 UTC, asleepingpanda commented
@rkdavidson this looks good to me. Looks like it's strictly an additive change, and the feature is locked behind a Feature Flag. We'll want to get this update pushed out before the client side update, so I'm good pushing this out!

2020-12-09 21:50 UTC, asleepingpanda requested changes

2020-12-09 21:50 UTC, asleepingpanda commented on src/data/live-stream/data-source.js
> +    console.log('[rkd] getStreamChatChannel:', getStreamChatChannel);
Remove unnecessary console.logs

2020-12-10 16:07 UTC, rkdavidson commented on src/data/live-stream/data-source.js
> +    console.log('[rkd] getStreamChatChannel:', getStreamChatChannel);
Good catch!

2020-12-16 15:04 UTC, merged