[Search] Refactor Algolia search to support multiple indices
christfellowshipchurch/apollos-api pull request #197
Opened 2021-01-13 19:42 UTC by rkdavidson

## DESCRIPTION
### 🚧 WIP 🚧

### 1. What does this PR do, or why is it needed?
The Apollos core package for Algolia search is coupled to the `ContentItem` type. There are several occurrences of "ContentItem" in [@apollosproject/data-connector-algolia-search](https://github.com/ApollosProject/apollos-apps/blob/master/packages/apollos-data-connector-algolia-search/src/data-source.js#L56).

That coupling prevents clean reuse of the Algolia search integrated `Search` dataSource for other data types, i.e. **Groups**.

This PR's primary goal is to add **Groups** index to Algolia.
In order to do that, a CF re-implementation of the Apollos core Search was required so multiple Algolia indices can coexist via the API.

Algolia indices are still configured in `config.yml`, but the `ALGOLIA` values (and relevant `env` vars) are refactored [here](https://github.com/christfellowshipchurch/apollos-api/compare/master...search-groups#diff-5a7db8dbadaef1b1b5a8738ba70b5ffac82b8e243732154165911284e08aad4b).

### 2. What design trade-offs/decisions were made?
WIP

### 3. How do I test this PR?

**New local `.env` values**
```
# Delete
ALGOLIA_SEARCH_INDEX=ContentItems

# Add
ALGOLIA_SEARCH_INDEX_CONTENT_ITEMS=ContentItems
ALGOLIA_SEARCH_INDEX_GROUPS=Groups
```

### 4. What automated tests did you write?

## SCREENSHOTS/GIFS

| iOS | Android | Web |
| --- | ------- | --- |
|     |         |     |

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, storybook, or apps
- [ ] Assign relevant reviewers
- [ ] Upload GIF(s) of iOS, Android, Web
- [ ] Get one peer approval before merging

## REVIEW:

**Manual QA**

- [ ] QA branch on iOS and ensure it looks/behaves as expected
- [ ] QA branch on Android and ensure it looks/behaves as expected
- [ ] QA branch on Web and ensure it looks/behaves as expected

**Code Review**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

2021-02-05 17:18 UTC, jordanwade approved these changes
👍 LGTM, checked this on iOS, web-app, web-app-v2 and everything seems to be working as expected. I'll leave it to @asleepingpanda for the final approval, just in case he sees any breaking changes. Nice Work @rkdavidson!

2021-02-08 15:32 UTC, rkdavidson commented
Hey @asleepingpanda , have you had a chance to review the changes in this yet? Specifically around the `ContentItem` mechanisms and indexing stuff?

2021-02-08 19:05 UTC, asleepingpanda requested changes

2021-02-08 19:05 UTC, asleepingpanda commented on config.yml
> +    # 🤔 Is it ok or acceptable to use TitleCase key names here?
once we get into the `CONFIGURATION` object, we're good to go back to lower camel case

2021-02-08 19:05 UTC, asleepingpanda commented on src/data/content-item/data-source.js
> +export default class ContentItem extends SearchableContentItem {
Hmmm.... idk how much I like this convention.

it seems backwards since search is a higher functionality of the Content Item class. In this convention above, it's written as though Content Item is an extension of the base Searchable class. Is there a way to invert this relationship?

2021-02-08 19:05 UTC, asleepingpanda commented on src/data/content-item/schema.js
> +  extend type Mutation {
Yeah so I'm getting a bit nervous with the manageability of this. If a change is needed to be made for search, I wonder how well understood it would be to go into each unique data type to configure it's search abilities. As opposed to managing all of these Index types from the Search datasource directory

2021-02-08 21:19 UTC, rkdavidson commented on config.yml
> +    # 🤔 Is it ok or acceptable to use TitleCase key names here?
Fixed in commit 0bb6a0e 👍

2021-02-08 21:42 UTC, rkdavidson commented on src/data/content-item/data-source.js
> +export default class ContentItem extends SearchableContentItem {
Fixed in commits 0bb6a0e and f3a03e5 by just pulling all that functionality up into `src/data/content-item/data-source.js` where it largely was in the first place.

I liked the idea of hiding all that search-specific logic into a separate, self-contained place for clarity — but it did feel awkward too relying on a class inheritance chain.

There's probably further room to centralize some utils like clamping object byte size and keyword extraction, but no immediate value right this second IMO.

2021-02-08 21:48 UTC, rkdavidson commented on src/data/content-item/schema.js
> +  extend type Mutation {
Fixed in commit 4b59956 , by consolidating the schema defs to the `src/data/search/schema.js` file instead.

Rambled about this on Slack, but, my rationale for keeping search-related schema changes local to the _things being searched_ is that the resolvers and data-source methods behind them are in the data types, anyway.

I.e. I can see from `search/schema.js` that groups are searchable, but in order to see how/where the implementation happens, I have to go over to `group-item/resolvers.js`. Again, possibly personal preference, but I find it confusing when things reach up and over into other things' cookie jars.

But if the pattern is inconsistent with Apollos core, I'd more strongly prefer to be consistent than match my subjective opinion.

I thought `CheckInable` works like my original approach, but I had it backwards in my head.

So does this commit 4b59956 address your concern?

2021-02-09 15:07 UTC, asleepingpanda requested changes

2021-02-09 15:07 UTC, asleepingpanda commented on src/data/search/schema.js
> +  input SearchGroupsInput {
Update the search input to `SearchQueryInput` with fields: `key: String!` and `values: [String]`

2021-02-09 19:55 UTC, merged